# --------------------------------------------------------------------------------------------------
# Azure CI pipeline.
# More info: https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# --------------------------------------------------------------------------------------------------

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: ci-keys

steps:
- script: ./ci/test.sh
  displayName: 'Test'

- script: ./ci/pack.sh
  displayName: 'Pack'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: xUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)/artifacts/xunit.results.xml'
  condition: always()
